### ISSUE TITLE
探讨下 动态表单的实现

### ISSUE THREAD

**Issue by shortybin** [raedev/android-forms#1]
看了下你的库是通过RecyclerView实现的动态表单。

我目前也有个动态表单的需求，后台管理系统配置表单项，我这边展示。我目前是通过一个LinearLayout去addview去实现的。因为我考虑的是这种表单项一般复用的情况很少。而且我们的单选和多选选项也不是固定的是、否。都是通过配置下发的。

还有就是这个动态表单的样式目前我看你的每一项都是左右结构，左边标题右边内容。如果两个系统都使用这个表单系统，但是另一个是上下结构的，上标题下内容。就需要重新再定义一个FormItem。

RecyclerView的性能可能稍微好些，addview的可扩展性应该更大一些。不知道我理解的对不对。

作者如果有微信或者QQ可以详细探讨一下，希望多多指教。

**Comment by raedev** [comment]
1、通过LinearLayout.addView()的方法是没有对复用View的，在数据量大的情况下会发生卡顿的情况，这种方式一般是不推荐的。
2、由于每个项目对表单的样式要求都是不同的，表单库大部分只是封装了对表单的操作（增删改查），样式则需要业务自己去自定义了。一般来说，大部分应用场景都提供了继承的方式来实现自己的业务，如自定义自己的EditTextFromItem。
3、基于Rv的表单库扩展性应该说是比较好了，基本上能满足很多的应用场景。而这个表单库的左右布局只是针对个人的业务上去实现的，在你的项目上则需要复杂一点重新实现一遍效果（很难做到一套通用的UI表单样式）。

**Comment by shortybin** [comment]
> 1、通过LinearLayout.addView()的方法是没有对复用View的，在数据量大的情况下会发生卡顿的情况，这种方式一般是不推荐的。 2、由于每个项目对表单的样式要求都是不同的，表单库大部分只是封装了对表单的操作（增删改查），样式则需要业务自己去自定义了。一般来说，大部分应用场景都提供了继承的方式来实现自己的业务，如自定义自己的EditTextFromItem。 3、基于Rv的表单库扩展性应该说是比较好了，基本上能满足很多的应用场景。而这个表单库的左右布局只是针对个人的业务上去实现的，在你的项目上则需要复杂一点重新实现一遍效果（很难做到一套通用的UI表单样式）。

我暂时做了个Demo，放到 https://github.com/shortybin/Forms
我觉得表单作为用户的填写信息功能，如果通过后台去配置表单项，如果100项也不会有太多性能问题。况且表单太多用户的体验就会差很多了。一个表单页最多应该不会超过30项内容。所以就直接用addView的方式去实现了。
感觉对于我这菜鸟来说addView相比RV的实现更好理解一点。技术水平有限暂时看你的封装还有点懵。

**Comment by raedev** [comment]
具体看你业务来决定啦，简单的话大可不必用到表单库来做了。附自定义表单步骤：
以上下的EditText（`EditTextFormItem2`）布局为例：

1. `EditTextFormItem2` 继承 `EditTextFormItem`
2. 重写以下方法
```kotlin
   override val layoutId: Int = R.layout.form_item_edit_text2
   // 类型自己定义，不要跟FormType重复即可
   override val formType: Int = 123123
  // 实现自己的方法
  override fun onBindViewHolder(holder: FormViewHolder){}
  override fun onBindViewEvent(holder: FormViewHolder){}
  override fun onUnBindViewEvent(holder: FormViewHolder){}
```
3、重写一个`FormRender`表单渲染器
```kotlin
open class YourFormRender<T : IEntityFormRender>(
    context: Context,
    adapter: FormGroupAdapter,
    fragmentManager: FragmentManager
) : FormRender(context, adapter, fragmentManager) {

    override fun render() {
        super.render()
        // 交给实体类渲染
        entity.onRender(this)
    }

    /**
     * 添加文本编辑框
     */
    protected open fun addEditText2(
        inputType: FormInputType,
        label: String, name: String, value: String? = null, required: Boolean = false,
        parent: FormItem? = null,
    ): EditTextFormItem {
        return EditTextFormItem2(inputType, label, name, value, required).addToFormGroup(parent)
    }
}
```

**Comment by shortybin** [comment]
> 具体看你业务来决定啦，简单的话大可不必用到表单库来做了。附自定义表单步骤： 以`EditTextFormItem2`为例：
> 
> 1. `EditTextFormItem2` 继承 `EditTextFormItem`
> 2. 重写以下方法
> 
> ```kotlin
>   override val layoutId: Int = R.layout.form_item_edit_text2
>   // 类型自己定义，不要跟FormType重复即可
>   override val formType: Int = 123123
>   // 实现自己的方法
>   override fun onBindViewHolder(holder: FormViewHolder){}
>   override fun onBindViewEvent(holder: FormViewHolder){}
>   override fun onUnBindViewEvent(holder: FormViewHolder){}
> ```
> 
> 3、重写一个`FormRender`表单渲染器
> 
> ```kotlin
> class YourFormRender(
>     context: Context,
>     adapter: FormGroupAdapter,
>     fragmentManager: FragmentManager
> ) : FormRender(context, adapter, fragmentManager) {
> 
>     /**
>      * 添加文本编辑框
>      */
>     protected open fun addEditText2(
>         inputType: FormInputType,
>         label: String, name: String, value: String? = null, required: Boolean = false,
>         parent: FormItem? = null,
>     ): EditTextFormItem {
>         return EditTextFormItem2(inputType, label, name, value, required).addToFormGroup(parent)
>     }
> }
> ```

感谢您的回复，我再看看你的库。

**Comment by shortybin** [comment]
> 具体看你业务来决定啦，简单的话大可不必用到表单库来做了。附自定义表单步骤： 以`EditTextFormItem2`为例：
> 
> 1. `EditTextFormItem2` 继承 `EditTextFormItem`
> 2. 重写以下方法
> 
> ```kotlin
>   override val layoutId: Int = R.layout.form_item_edit_text2
>   // 类型自己定义，不要跟FormType重复即可
>   override val formType: Int = 123123
>   // 实现自己的方法
>   override fun onBindViewHolder(holder: FormViewHolder){}
>   override fun onBindViewEvent(holder: FormViewHolder){}
>   override fun onUnBindViewEvent(holder: FormViewHolder){}
> ```
> 
> 3、重写一个`FormRender`表单渲染器
> 
> ```kotlin
> class YourFormRender(
>     context: Context,
>     adapter: FormGroupAdapter,
>     fragmentManager: FragmentManager
> ) : FormRender(context, adapter, fragmentManager) {
> 
>     /**
>      * 添加文本编辑框
>      */
>     protected open fun addEditText2(
>         inputType: FormInputType,
>         label: String, name: String, value: String? = null, required: Boolean = false,
>         parent: FormItem? = null,
>     ): EditTextFormItem {
>         return EditTextFormItem2(inputType, label, name, value, required).addToFormGroup(parent)
>     }
> }
> ```

今天又仔细看了下你的库，封装的很nice。对于正常的表单来说很满足了。但是我们的表单设计的很复杂，也有你这种的父子关联表单，除此之外，单选多选支持从接口获取数据和本地获取数据两种情况。输入框还要支持接口联想内容。设计的太复杂了。
https://mrhj.gitee.io/form-generator/#/ 可以看这个，完全都是自定义配置，根据生成的Json生成表单。还参考了市面上的产品 轻流、简道云的功能。
这种复杂的一般都是前端搞，APP嵌入H5。用原生搞确实有点复杂。
