### ISSUE TITLE
Jitpack中无法搜到generator，gradle下载失败

### ISSUE THREAD

**Issue by UniqHu** [raedev/android-forms#3]
Could not resolve com.github.raedev> Could not get resource 'https://jitpac> Could not GET 'https://jitpack.forms-aeneraton/1.
.1/android-forms-generator-1.0.1.pom'. Received status code 401 from server: Unauthorizec

**Comment by UniqHu** [comment]
form 和 gererator库 都在再不下来咋办  ~

**Comment by raedev** [comment]
可以先换一下我的私库，私库版本为开发版本，不是很稳定。或者你自己可以打包成aar引用。
``` gradle
    repositories {
        maven { url 'https://maven.raeblog.com/repository/public' }
    }
```

**Comment by UniqHu** [comment]
很强
